import SwiftUI
import UIKit

extension Color {
    // MARK: - New Collors
    // Main collors
    static let chineseBlack = Color(uiColor: .chineseBlack)
    static let chineseBlackLoad = Color(uiColor: .chineseBlackLoad)
    static let chineseBlack04 = Color(uiColor: .chineseBlack04)
    static let chineseShadow = Color(uiColor: .chineseShadow)
    static let romanSilver = Color(uiColor: .romanSilver)
    static let romanSilver07 = Color(uiColor: .romanSilver07)
    static let romanSilver01 = Color(uiColor: .romanSilver01)
    static let bone = Color(uiColor: .bone)
    static let brightGray = Color(uiColor: .brightGray)
    static let gainsboro = Color(uiColor: .gainsboro)
    static let aliceBlue = Color(uiColor: .aliceBlue)
    static let antiFlashWhite = Color(uiColor: .antiFlashWhite)
    static let water = Color(uiColor: .water)
    static let diamond = Color(uiColor: .diamond)
    static let beauBlue = Color(uiColor: .beauBlue)
    static let brilliantAzure = Color(uiColor: .brilliantAzure)
    static let dodgerBlue = Color(uiColor: .dodgerBlue)
    static let dodgerTransBlue = Color(uiColor: .dodgerTransBlue)
    static let white = Color(uiColor: .white )
    static let transWhite = Color(uiColor: .transWhite )
    static let greenCrayola = Color(uiColor: .greenCrayola)
    static let spanishCrimson = Color(uiColor: .spanishCrimson)
    static let spanishCrimson01 = Color(uiColor: .spanishCrimson01)
    static let royalOrange = Color(uiColor: .royalOrange)
    static let osloGrayApprox = Color(uiColor: .osloGrayApprox)
    // Shadow collors
    static let outerSpace = Color(uiColor: .outerSpace)
    static let auroMetalSaurus = Color(uiColor: .auroMetalSaurus)
    static let smokyStudio = Color(uiColor: .smokyStudio)
    static let manatee = Color(uiColor: .manatee)
    static let metallicSilver = Color(uiColor: .metallicSilver)
    static let ashGray = Color(uiColor: .ashGray)
    static let lightGray = Color(uiColor: .lightGray)
    static let ghostWhite = Color(uiColor: .ghostWhite)
    static let ghostWhite04 = Color(uiColor: .ghostWhite04)
    static let bubbles = Color(uiColor: .bubbles)
    static let seaGreen = Color(uiColor: .seaGreen)
    static let philippineBronze = Color(uiColor: .philippineBronze)
    // Main dark collors
    static let cultured = Color(uiColor: .cultured)
    static let dimGray = Color(uiColor: .dimGray)
    static let eerieBlack = Color(uiColor: .eerieBlack)
    static let darkJungleGreen = Color(uiColor: .darkJungleGreen)
    static let charcoal = Color(uiColor: .charcoal)
    static let lapisLazuli = Color(uiColor: .lapisLazuli)
    static let queenBlue = Color(uiColor: .queenBlue)
    static let slateGray = Color(uiColor: .slateGray)
    static let outOfTheBlue = Color(uiColor: .outOfTheBlue)
    static let dynamicBlack = Color(uiColor: .dynamicBlack)
    static let greenPigment = Color(uiColor: .greenPigment)
    static let сardinal = Color(uiColor: .сardinal)
    static let chineseBronze = Color(uiColor: .chineseBronze)
    // Shadow dark collors
    static let lunarShadow = Color(uiColor: .lunarShadow)
    static let nickel = Color(uiColor: .nickel)
    static let blackCoral = Color(uiColor: .blackCoral)
    static let davysGrey = Color(uiColor: .davysGrey)
    static let charlestonGreen = Color(uiColor: .charlestonGreen)
    static let vampireBlack = Color(uiColor: .vampireBlack)
    static let policeBlue = Color(uiColor: .policeBlue)
    // MARK: - Old ones
    static let blackSqueezeApprox = Color(uiColor: .blackSqueezeApprox)
    static let dodgerBlueApprox = Color(uiColor: .dodgerBlueApprox)
    static let onahauApprox = Color(uiColor: .onahauApprox)
    static let zeroColor = Color(uiColor: .zeroColor)
    static let sailApprox = Color(uiColor: .sailApprox)
    static let cornflowerBlueApprox = Color(uiColor: .cornflowerBlueApprox)
    static let alabasterSolid = Color(uiColor: .alabasterSolid)
    static let azureRadianceApprox = Color(uiColor: .azureRadianceApprox)
    static let hawkesBlueApprox = Color(uiColor: .hawkesBlueApprox)
    static let pigeonPostApprox = Color(uiColor: .pigeonPostApprox)
    static let nobelApprox = Color(uiColor: .nobelApprox)
    static let tundoraApprox = Color(uiColor: .tundoraApprox)
    static let manateeApprox = Color(uiColor: .manateeApprox)
    static let sharkApprox = Color(uiColor: .sharkApprox)
    static let athensGrayApprox = Color(uiColor: .athensGrayApprox)
    static let ironApprox = Color(uiColor: .ironApprox)
    static let regentGrayApprox = Color(uiColor: .regentGrayApprox)
    static let woodSmokeApprox = Color(uiColor: .woodSmokeApprox)
    static let jaffaApprox = Color(uiColor: .jaffaApprox)
    static let amaranthApprox = Color(uiColor: .amaranthApprox)
    static let bombayApprox = Color(uiColor: .bombayApprox)
    static let blackHazeApprox = Color(uiColor: .blackHazeApprox)
    static let white06 = Color(uiColor: .white06)
    static let polarApprox = Color(uiColor: .polarApprox)
    static let jungleGreenApprox = Color(uiColor: .jungleGreenApprox)
}
