# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'CryptoMessenger' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CryptoMessenger

  # Matrix core
	pod 'JitsiMeetSDK', '~> 7.0.1'
	pod 'SwiftJWT', '~> 3.6.200'

  # Firebase
  pod 'Firebase/RemoteConfig'

  # Resources
  pod 'R.swift'

  # Layout
  pod 'SnapKit'

  # Image loading/caching
  pod 'Mantis', '~> 1.9.0'

  # Code style
  pod 'SwiftLint'

  # Phone formatter
  pod 'PhoneNumberKit'
  pod 'SPStorkController'

  #Crypto
  pod 'HDWalletKit'
  pod 'Bip39.swift'

  pod 'SweeterSwift'
  
  # Baidu
  pod 'BaiduMapKit', '6.0.0'

	pod 'AFNetworking', '~> 4.0.0'
	pod 'GZIP', '~> 1.3.0'
	pod 'SwiftyBeaver', '1.9.5'
	pod 'OLMKit', '~> 3.2.5', :inhibit_warnings => true
	pod 'Realm', '10.27.0'
	pod 'libbase58', '~> 0.1.4'
	pod 'MatrixSDKCrypto', "0.1.0", :configurations => ['DEBUG']
	pod 'OHHTTPStubs', '~> 9.1.0'

end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ENABLE_BITCODE'] = 'NO'
	   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
		end
	end
end
